/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 11-Sep-2023 3:30:54 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_EvaluasiAkip_Periode]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [EvaluasiAkip] DROP CONSTRAINT [FK_EvaluasiAkip_Periode]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HasilEvaluasi_EvaluasiAkip]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HasilEvaluasi] DROP CONSTRAINT [FK_HasilEvaluasi_EvaluasiAkip]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UploadFile_EvaluasiAkip]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UploadFile] DROP CONSTRAINT [FK_UploadFile_EvaluasiAkip]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UploadFile_KategoriDokumen]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UploadFile] DROP CONSTRAINT [FK_UploadFile_KategoriDokumen]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[EvaluasiAkip]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [EvaluasiAkip]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[HasilEvaluasi]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [HasilEvaluasi]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[KategoriDokumen]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [KategoriDokumen]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UploadFile]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UploadFile]
GO

/* Create Tables */

CREATE TABLE [EvaluasiAkip]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[TanggalAjuan] date,
	[IdPeriode] int,
	[Status] varchar(50),
	[Keterangan] text
)
GO

CREATE TABLE [HasilEvaluasi]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[IdEvaluasiAkip] int,
	[TanggalEvaluasi] date,
	[FilePath] text,
	[Status] varchar(50),
	[Keterangan] text,
	[Evaluator] varchar(250)
)
GO

CREATE TABLE [KategoriDokumen]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Komponen] text
)
GO

CREATE TABLE [UploadFile]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[FilePath] text,
	[NamaDokumen] text,
	[IdKategoriDokumen] int,
	[UploadDate] date,
	[Deskripsi] text,
	[IdEvaluasiAkip] int,
	[Revisi] int
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [EvaluasiAkip] 
 ADD CONSTRAINT [PK_EvaluasiAkip]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_EvaluasiAkip_Periode] 
 ON [EvaluasiAkip] ([IdPeriode] ASC)
GO

ALTER TABLE [HasilEvaluasi] 
 ADD CONSTRAINT [PK_HasilEvaluasi]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_HasilEvaluasi_EvaluasiAkip] 
 ON [HasilEvaluasi] ([IdEvaluasiAkip] ASC)
GO

ALTER TABLE [KategoriDokumen] 
 ADD CONSTRAINT [PK_KategoriDokumen]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [UploadFile] 
 ADD CONSTRAINT [PK_UploadFile]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UploadFile_EvaluasiAkip] 
 ON [UploadFile] ([IdEvaluasiAkip] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UploadFile_KategoriDokumen] 
 ON [UploadFile] ([IdKategoriDokumen] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [EvaluasiAkip] ADD CONSTRAINT [FK_EvaluasiAkip_Periode]
	FOREIGN KEY ([IdPeriode]) REFERENCES [Periode] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HasilEvaluasi] ADD CONSTRAINT [FK_HasilEvaluasi_EvaluasiAkip]
	FOREIGN KEY ([IdEvaluasiAkip]) REFERENCES [EvaluasiAkip] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UploadFile] ADD CONSTRAINT [FK_UploadFile_EvaluasiAkip]
	FOREIGN KEY ([IdEvaluasiAkip]) REFERENCES [EvaluasiAkip] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UploadFile] ADD CONSTRAINT [FK_UploadFile_KategoriDokumen]
	FOREIGN KEY ([IdKategoriDokumen]) REFERENCES [KategoriDokumen] ([Id]) ON DELETE No Action ON UPDATE No Action
GO
