/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 13-Sep-2023 8:14:10 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_evaluasi_akip_periode]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [evaluasi_akip] DROP CONSTRAINT [FK_evaluasi_akip_periode]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_hasil_evaluasi_evaluasi_akip]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [hasil_evaluasi] DROP CONSTRAINT [FK_hasil_evaluasi_evaluasi_akip]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_indikator_periode_indikator]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [indikator_periode] DROP CONSTRAINT [FK_indikator_periode_indikator]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_indikator_periode_level]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [indikator_periode] DROP CONSTRAINT [FK_indikator_periode_level]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_indikator_periode_periode]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [indikator_periode] DROP CONSTRAINT [FK_indikator_periode_periode]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_indikator_periode_pic]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [indikator_periode] DROP CONSTRAINT [FK_indikator_periode_pic]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_laporan_capaian_indikator_periode]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [laporan_capaian] DROP CONSTRAINT [FK_laporan_capaian_indikator_periode]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_laporan_capaian_kategori_kinerja]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [laporan_capaian] DROP CONSTRAINT [FK_laporan_capaian_kategori_kinerja]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_laporan_capaian_periode]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [laporan_capaian] DROP CONSTRAINT [FK_laporan_capaian_periode]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_laporan_capaian_triwulan]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [laporan_capaian] DROP CONSTRAINT [FK_laporan_capaian_triwulan]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_upload_file_evaluasi_akip]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [upload_file] DROP CONSTRAINT [FK_upload_file_evaluasi_akip]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_upload_file_kategori_dokumen]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [upload_file] DROP CONSTRAINT [FK_upload_file_kategori_dokumen]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[evaluasi_akip]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [evaluasi_akip]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[hasil_evaluasi]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [hasil_evaluasi]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[indikator]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [indikator]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[indikator_periode]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [indikator_periode]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[kategori_dokumen]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [kategori_dokumen]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[kategori_kinerja]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [kategori_kinerja]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[laporan_capaian]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [laporan_capaian]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[level]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [level]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[periode]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [periode]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[pic]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [pic]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[satuan]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [satuan]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[triwulan]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [triwulan]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[upload_file]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [upload_file]
GO

/* Create Tables */

CREATE TABLE [evaluasi_akip]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[tanggal_ajuan] date,
	[periode_id] int,
	[status] varchar(50),
	[keterangan] text
)
GO

CREATE TABLE [hasil_evaluasi]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[evaluasi_akip_id] int,
	[tanggal_evaluasi] date,
	[file_path] text,
	[status] varchar(50),
	[keterangan] text,
	[evaluator] varchar(250)
)
GO

CREATE TABLE [indikator]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nama_indikator] varchar(500),
	[satuan_id] int
)
GO

CREATE TABLE [indikator_periode]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[indikator_id] int,
	[periode_id] int,
	[target] float,
	[pic_id] int,
	[level_id] int
)
GO

CREATE TABLE [kategori_dokumen]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[kategori_komponen] text
)
GO

CREATE TABLE [kategori_kinerja]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nama_kategori_kinerja] varchar(50)
)
GO

CREATE TABLE [laporan_capaian]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[indikator_periode_id] int,
	[triwulan_id] int,
	[realisasi] float,
	[kinerja] float,
	[periode_id] int,
	[kategori_kinerja_id] int,
	[sumber_data] text
)
GO

CREATE TABLE [level]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nama_level] varchar(500)
)
GO

CREATE TABLE [periode]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[periode] numeric(18),
	[status] varchar(50)
)
GO

CREATE TABLE [pic]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nama_pic] varchar(500),
	[keterangan] text
)
GO

CREATE TABLE [satuan]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nama_satuan] varchar(500)
)
GO

CREATE TABLE [triwulan]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[triwulan] varchar(50)
)
GO

CREATE TABLE [upload_file]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[file_path] text,
	[nama_dokumen] text,
	[kategori_dokumen_id] int,
	[upload_date] date,
	[deskripsi] text,
	[evaluasi_akip_id] int,
	[revisi] int
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [evaluasi_akip] 
 ADD CONSTRAINT [PK_evaluasi_akip]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_evaluasi_akip_periode] 
 ON [evaluasi_akip] ([periode_id] ASC)
GO

ALTER TABLE [hasil_evaluasi] 
 ADD CONSTRAINT [PK_hasil_evaluasi]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_hasil_evaluasi_evaluasi_akip] 
 ON [hasil_evaluasi] ([evaluasi_akip_id] ASC)
GO

ALTER TABLE [indikator] 
 ADD CONSTRAINT [PK_indikator]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_indikator_satuan] 
 ON [indikator] ([satuan_id] ASC)
GO

ALTER TABLE [indikator_periode] 
 ADD CONSTRAINT [PK_indikator_periode]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_indikator_periode_indikator] 
 ON [indikator_periode] ([indikator_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_indikator_periode_level] 
 ON [indikator_periode] ([level_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_indikator_periode_periode] 
 ON [indikator_periode] ([periode_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_indikator_periode_pic] 
 ON [indikator_periode] ([pic_id] ASC)
GO

ALTER TABLE [kategori_dokumen] 
 ADD CONSTRAINT [PK_kategori_dokumen]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [kategori_kinerja] 
 ADD CONSTRAINT [PK_kategori_kinerja]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [laporan_capaian] 
 ADD CONSTRAINT [PK_laporan_capaian]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_laporan_capaian_indikator_periode] 
 ON [laporan_capaian] ([indikator_periode_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_laporan_capaian_kategori_kinerja] 
 ON [laporan_capaian] ([kategori_kinerja_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_laporan_capaian_periode] 
 ON [laporan_capaian] ([periode_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_laporan_capaian_triwulan] 
 ON [laporan_capaian] ([triwulan_id] ASC)
GO

ALTER TABLE [level] 
 ADD CONSTRAINT [PK_level]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [periode] 
 ADD CONSTRAINT [PK_periode]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [pic] 
 ADD CONSTRAINT [PK_pic]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [satuan] 
 ADD CONSTRAINT [PK_satuan]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [triwulan] 
 ADD CONSTRAINT [PK_triwulan]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [upload_file] 
 ADD CONSTRAINT [PK_upload_file]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_upload_file_evaluasi_akip] 
 ON [upload_file] ([evaluasi_akip_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_upload_file_kategori_dokumen] 
 ON [upload_file] ([kategori_dokumen_id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [evaluasi_akip] ADD CONSTRAINT [FK_evaluasi_akip_periode]
	FOREIGN KEY ([periode_id]) REFERENCES [periode] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [hasil_evaluasi] ADD CONSTRAINT [FK_hasil_evaluasi_evaluasi_akip]
	FOREIGN KEY ([evaluasi_akip_id]) REFERENCES [evaluasi_akip] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [indikator_periode] ADD CONSTRAINT [FK_indikator_periode_indikator]
	FOREIGN KEY ([indikator_id]) REFERENCES [indikator] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [indikator_periode] ADD CONSTRAINT [FK_indikator_periode_level]
	FOREIGN KEY ([level_id]) REFERENCES [level] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [indikator_periode] ADD CONSTRAINT [FK_indikator_periode_periode]
	FOREIGN KEY ([periode_id]) REFERENCES [periode] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [indikator_periode] ADD CONSTRAINT [FK_indikator_periode_pic]
	FOREIGN KEY ([pic_id]) REFERENCES [pic] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [laporan_capaian] ADD CONSTRAINT [FK_laporan_capaian_indikator_periode]
	FOREIGN KEY ([indikator_periode_id]) REFERENCES [indikator_periode] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [laporan_capaian] ADD CONSTRAINT [FK_laporan_capaian_kategori_kinerja]
	FOREIGN KEY ([kategori_kinerja_id]) REFERENCES [kategori_kinerja] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [laporan_capaian] ADD CONSTRAINT [FK_laporan_capaian_periode]
	FOREIGN KEY ([periode_id]) REFERENCES [periode] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [laporan_capaian] ADD CONSTRAINT [FK_laporan_capaian_triwulan]
	FOREIGN KEY ([triwulan_id]) REFERENCES [triwulan] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [upload_file] ADD CONSTRAINT [FK_upload_file_evaluasi_akip]
	FOREIGN KEY ([evaluasi_akip_id]) REFERENCES [evaluasi_akip] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [upload_file] ADD CONSTRAINT [FK_upload_file_kategori_dokumen]
	FOREIGN KEY ([kategori_dokumen_id]) REFERENCES [kategori_dokumen] ([id]) ON DELETE No Action ON UPDATE No Action
GO
